### ISSUE TITLE
Errors in Windows

### ISSUE THREAD

**Issue by amcdnl** [capaj/chokidar-socket-emitter#12]
When I run it with gulp in windows I get the following error:

```
cat@WINDOWS C:\dev\Web
$ gulp hmr
[08:02:28] Using gulpfile C:\dev\Web\gulpfile.js
[08:02:28] Starting 'hmr'...
[08:02:28] 'hmr' errored after 1.21 ms
[08:02:28] Error: Cannot find module 'C:\Users\cat\AppData\Roaming\nvm\v5.6.0\node_modules\gulp\bin\package.json'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at module.exports.chokidar.watch.on.io.on.close (C:\dev\Web\node_modules\chokidar-socket-emitter\server.js:8:17)
  at Gulp.<anonymous> (C:\dev\Web\tasks\serve.js:36:3)
  at module.exports (C:\dev\Web\node_modules\orchestrator\lib\runTask.js:34:7)
  at Gulp.Orchestrator._runTask (C:\dev\Web\node_modules\orchestrator\index.js:273:3)
  at Gulp.Orchestrator._runStep (C:\dev\Web\node_modules\orchestrator\index.js:214:10)
  at Gulp.Orchestrator.start (C:\dev\Web\node_modules\orchestrator\index.js:134:8)
  at C:\Users\AppData\Roaming\nvm\v5.6.0\node_modules\gulp\bin\gulp.js:129:20
  at nextTickCallbackWith0Args (node.js:453:9)
  at process._tickCallback (node.js:382:13)
  at Function.Module.runMain (module.js:449:11)
  at startup (node.js:140:18)
  at node.js:1001:3
```

my task is ultra simple:

```
gulp.task('hmr', function() {
  chokidarEvEmitter({port: 8090});
});
```

versions of everything are:
- NodeJS 5.6.0
- NPM 3.6.0
- Gulp 3.9.1
- chokidar-socket-emitter 0.4.2

it does seem to work fine on windows and you can observe that with this demo project: https://github.com/capaj/NG6-starter/tree/jspm . 

_Note_: If I run it from the command line installed globally it does work fine.

**Comment by capaj** [comment]
it is trying to find package.json on wrong path. Thanks for reporting. Will put a try catch block around it. 
After the fix, it might end up watching a directory: 'C:\Users\cat\AppData\Roaming\nvm\v5.6.0\node_modules\gulp\bin\

For you. You might want to put `C:\dev\Web` into your opts like:

```
gulp.task('hmr', function() {
  chokidarEvEmitter({port: 8090, dir: 'C:\dev\Web'});
});
```

**Comment by amcdnl** [comment]
Thanks!!
