### ISSUE TITLE
Error: watch jspm_packages/npm/fbjs@0.3.2/lib/__mocks__/fetch.js ENOSPC

### ISSUE THREAD

**Issue by peteruithoven** [capaj/chokidar-socket-emitter#6]
On Elementary OS I get the following error when starting the following script:

``` javascript
'use strict';
const httpServer = require('http-server');
const server = httpServer.createServer({
  cache: -1,
  robots: true,
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Credentials': 'true'
  }
});

require('chokidar-socket-emitter')({ app: server.server });

server.listen(3000);

console.log('Visit: localhost:3000');
```

```
$ nodejs server.js 
Visit: localhost:3000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch jspm_packages/npm/fbjs@0.3.2/flow/include/nullthrows.js ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/peteruithoven/Projects/Doodle3D/dev/Doodle3D-App/node_modules/chokidar-socket-emitter/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/peteruithoven/Projects/Doodle3D/dev/Doodle3D-App/node_modules/chokidar-socket-emitter/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/peteruithoven/Projects/Doodle3D/dev/Doodle3D-App/node_modules/chokidar-socket-emitter/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/peteruithoven/Projects/Doodle3D/dev/Doodle3D-App/node_modules/chokidar-socket-emitter/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/peteruithoven/Projects/Doodle3D/dev/Doodle3D-App/node_modules/chokidar-socket-emitter/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Could it be that it's also trying to watch all the files in `node_modules` and `jspm_packages`?

**Comment by peteruithoven** [comment]
Ignoring node_modules and jspm_packages seems to help, could we make this a default?

``` javascript
require('chokidar-socket-emitter')({
  app: server.server,
  chokidar: {
    ignored: [/[\/\\]\./, 'node_modules/**', 'jspm_packages/**']
  }
});
```

**Comment by capaj** [comment]
@peteruithoven that is not a bad idea. Just ran into the same problem, will do for 0.3.1.

**Comment by capaj** [comment]
fixed in https://github.com/capaj/chokidar-socket-emitter/commit/706c2f739b44fd83a899d39c078f4fbe9449b691
